/** ADR 14.2·14.4 차단 항목을 이용자가 읽을 수 있는 말로 옮긴다. */
export const BLOCKER_LABEL: Record<string, string> = {
  "B-MODEL-01": "생성 모델의 응답 형식·비용",
  "B-EMBED-01": "임베딩 1차 후보 검색",
  "B-RETRIEVAL-01": "공식 자료 결합 검색 품질",
  "B-OCR-01": "이미지·스캔 PDF 글자 인식 정확도",
  "B-FILE-SAFETY": "파일 안전성 격리 시험",
  "B-CONSENT-01": "외부 OCR 동의와 전송 차단",
  "B-STORAGE-01": "업로드 저장소 접근 권한",
  "B-DELETE-01": "원본·인식 결과 삭제",
  "B-SUPABASE-01": "데이터베이스 구조·권한 대조",
  "B-PROCESSOR-PRIVACY": "외부 제공자 개인정보 처리 조건",
  "B-PRIVACY-VERCEL": "호스팅 개인정보 처리 조건",
  "B-LAW-01": "법제처 접근 조건",
  "B-SOURCE-02": "공공데이터 공식 자료 수집",
  "B-SOURCE-03": "햇살론15 상품·취급기관 자료",
  "B-JOB-01": "작업 장애·재시도·취소 복구",
  "B-RATE-01": "호출 한도와 비용 원장",
  "B-DEADLINE-01": "입력별 처리 기한",
  "B-HEALTH-01": "서비스 상태 확인 경로",
  "B-RUNTIME-01": "실행 환경",
  "B-SPIKE-01": "전체 구성요소 연결 시험",
  "B-DEMO-01": "비회원 체험의 실제 실행",
  "B-E2E-01": "회원 전체 이용 과정",
  "B-BUILD-01": "배포 빌드·보안 점검",
  "B-CLAIM-01": "항목 판정 품질 평가",
};
